apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-role
rules:
- apiGroups: [""]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: portal
roleRef:
  kind: ClusterRole
  name: argocd-application-controller-role
  apiGroup: rbac.authorization.k8s.io
