apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nandinichatterjee/py-dev-nandini-12/nginx:latest
        ports:
        - containerPort: 80
