apiVersion: v1
kind: Service
metadata:
  name: myplugin-service
  namespace: portal
spec:
  selector:
    app: myplugin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Use "LoadBalancer" if you want to expose the service externally
